apiVersion: v1
kind: Service
metadata:
  name: discoveryservice-server
spec:
  selector:
    app: discoveryservice-server
  ports:
  - port: 9090
    targetPort: 9900
    protocol: TCP
    name: http
  externalIPs:
  - 192.168.11.101
