apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
      - name: discovery
        image: docker.io/aderenbach/discoveryservice 
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 9900
        
