apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: rc
  name: rc-zookeeper
  labels:
    application: zookeeper
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "rc-zookeeper"
  glusterfs:
    endpoints: gluster-cluster
    path: /rc-zookeeper
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: rc
  name: rc-zookeeper-log
  labels:
    application: zookeeper-log
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "rc-zookeeper-log"
  glusterfs:
    endpoints: gluster-cluster
    path: /rc-zookeeper-log
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
