apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rc
  name: rc-zookeeper
  labels:
    application: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "rc-zookeeper"
  resources:
     requests:
       storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rc
  name: rc-zookeeper-log
  labels:
    application: zookeeper-log
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "rc-zookeeper-log"
  resources:
     requests:
       storage: 2Gi
