---
kind: List
apiVersion: v1
items:
- kind: Endpoints
  apiVersion: v1
  metadata:
    namespace: rc
    name: gluster-cluster
    labels:
      env: rc
      module: system
      app: gluster-cluster
  subsets:
  - addresses:
    - ip: 172.16.10.160
    ports:
    - port: 24007
  - addresses:
    - ip: 172.16.10.183
    ports:
    - port: 24007
- kind: Service
  apiVersion: v1
  metadata:
    namespace: rc
    name: gluster-cluster
    labels:
      env: rc
      module: system
      app: gluster-cluster
  spec:
    ports:
      - port: 24007
