kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    module: service
    application: mysql
spec:
  type: NodePort
  selector:
    module: service
    application: mysql
  ports:
  - name: mysql
    port: 3306 
    targetPort: 3306
    nodePort: 30001
