apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: rc
  name: kafka
  labels:
    env: rc
    module: cores
    application: kafka
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        env: rc
        module: cores
        application: kafka
    spec:
      imagePullSecrets:
      - name: rc-secret
      containers:
      - name: kafka
        image: 172.16.105.147:5000/saas/dev/cores/kafka:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka.rc.svc.cluster.local"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.rc.svc.cluster.local:2181"
        - name: KAFKA_PORT
          value: "9092"
        - name:  KAFKA_HEALTHCHECK_TIMEOUT
          value: "30000"
        - name: KAFKA_REQUEST_TIMEOUT_MS
          value: "65000"
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: data
          mountPath: /kafka
      volumes:
      - name: dockersock
        hostPath: 
          path: /var/run/docker.sock
      - name: data
        persistentVolumeClaim:
          claimName: rc-kafka
