apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: rc
  name: rc-kafka
  labels:
    application: kafka
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "rc-kafka"
  glusterfs:
    endpoints: gluster-cluster
    path: /rc-kafka
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
