kind: Service
apiVersion: v1
metadata:
  namespace: rc
  name: kafka
  labels:
    env: rc
    module: cores
    application: kafka
spec:
  selector:
    env: rc
    module: cores
    application: kafka
  ports:
  - name: http
    protocol: TCP
    port: 9092
    targetPort: 9092
#  externalIPs:
#  - 192.168.0.236
