apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-ops
  labels:
    k8s-app: prometheus
spec:
  selector:
    k8s-app: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: http
  externalIPs:
  - 192.168.11.10
