kind: Service
apiVersion: v1
metadata:
  namespace: rc
  name: redis
  labels:
    env: rc
    module: cores
    application: redis
spec:
  selector:
    env: rc
    module: cores
    application: redis
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379
#  externalIPs:
#  - 192.168.0.236
