apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: production-spaceservice
  labels:
    env: production
    module: service
    application: spaceservice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: production-spaceservice
  resources:
     requests:
       storage: 1Gi
